spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plantify_cart
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update    
eureka:  client:    serviceUrl:      defaultZone: http://localhost:8761/eureka/    register-with-eureka: true
    fetch-registry: true
feign:
  hystrix:
    enabled: true

         
      